"""Event-tag rules (first match wins, most specific first). Matched against the TITLE only.

Every pattern is compiled with a word-start guard, so a rule can never fire in the middle of a word
("sue" in "issue", "opec" in "alopecia"). Stems still work at a word start ("acquir" matches "acquired").
Add a rule together with a gold-set item or a unit test that needs it; check with analysis/eval_gold.py.
"""

EVENT_RULES = [
    ("opinion", r"\?\s*$|should you buy|stocks? to buy|to buy (?:and hold|now|today|before)|buy and hold|best (?:stocks|dividend|etfs?)|how many shares|millionaire|passive[- ]income|reasons to (?:buy|add|own|avoid)|is it (?:too late|a good time)|can .{0,40} (?:reach|hit|double|soar) \$|\d+ (?:top |best |large[- ]cap )?(?:stocks|etfs|dividend|reasons|things|secrets)|forever|could make you|dividend (?:king|aristocrat)s?|vs\. |which (?:stock|etf|reit) is (?:better|the better)|is it time to|what you should know|key facts|here's why|here is why|here's what|if you (?:invest|had invested|put)|what a \$[\d,]+|pays you|\$[\d,]+ (?:per|a) month|invest(?:ed|ing)? \$[\d,]+|highest-yielding|prediction:|primed to|poised to|skyrocket|no-brainer|hand over fist|bargain|undervalued|overvalued|stay cheap|history says|will happen with|could be worth|worth this much|investing radar|on your radar|energize your portfolio|(?:for|in) your portfolio|in check|bullish on|optimistic|opportunity\b|sentiment shift|inflection point|fuel the next|next growth|growth phase|facts worth knowing|worth knowing|surpasses market returns|since last earnings|after the pullback|could tell investors|one number|strong growth stock|style scores|zacks|winning ai strategy|this market signal|reasons to be|a great position to|the 1 i'm buying|the next decade|what it would take|what would it take|what investors need|every .{0,20} investor needs|dividend-paying|wealth transfer|\b\d+ (?:[\w-]+ ){0,3}stocks?\b|we (?:avoid|ignore|brush off|turn down|keep off)|steer clear|off our radar|facing (?:headwinds|challenges)|worth your attention|worth watching|stocks? in focus|^links \d"),
    ("insider", r"\b(?:ceo|cfo|coo|cto|president|director|chairman|officer|evp|svp|insider|founder)\b.{0,60}\b(?:sells?|sold|buys?|bought|purchases?)\b.{0,40}(?:stock|shares)|\b(?:sells?|sold|buys?|bought)\b \$[\d,.]+[mk]? (?:in|of|worth)"),
    ("restatement", r"restat|non-reliance|accounting irregular|material weakness|sec investigation|subpoena"),
    ("cyber", r"cyber ?attack|data breach|ransomware|hacked|security incident|phishing|malware|scam"),
    ("bankruptcy", r"bankrupt|chapter 11|insolven|going concern|default(?:s|ed)? on"),
    ("leadership", r"\bceo\b.*(?:step|resign|retir|appoint|named|succe)|(?:step|resign|retir|appoint|named|succe).*\bceo\b|\bcfo\b.*(?:step|resign|appoint|named)|(?:step|resign|appoint|named).*\bcfo\b|chairman.*(?:step|resign|named)|executive (?:departure|shake)|president.*(?:resign|named)|new cfo|new ceo"),
    ("m&a", r"acquir|acquisition|takeover|merger|to buy .{0,40}(?:for|in) \$|buyout|bid for|divest|spin-?off|spinoff|joint venture|stake in|tie[- ]up"),
    ("guidance", r"guidance|outlook|forecast(?:s|ed)? (?:cut|raise|lower|higher)|raises? (?:its )?(?:full-year|annual|fy|q\d)|lowers? (?:its )?(?:full-year|annual|fy|q\d)|cuts? (?:its )?(?:full-year|annual|fy|q\d)|expects? (?:revenue|sales|earnings|profit)|reaffirm|growth target"),
    ("earnings", r"earnings|\beps\b|quarterly (?:results|sales|revenue|profit)|q[1-4] results|results for the (?:first|second|third|fourth)|revenue (?:beat|miss|rose|fell|grew|jumped)|profit (?:rose|fell|jumped|beat|missed)|beats? estimates|misses? estimates|tops? estimates|misses? by|beats? by|sales (?:jump|rise|fall|climb|slip)|reports? (?:q[1-4]|quarter)"),
    ("agreement", r"secures?\b.{0,40}(?:contract|deal|order)|contracts?\b|deal gets|awarded|(?:wins|lands|inks|signs?)\b.{0,30}(?:deal|contract|order|agreement)|partnership|teams? up|strategic (?:deal|agreement)|agreement with|orders? (?:from|for)"),
    ("capital", r"buyback|repurchase|(?:raises?|cuts?|hikes?|boosts?|declares?|suspends?|initiates?|increases?|omits?)\s+(?:its\s+|quarterly\s+|annual\s+|special\s+)?dividend|dividend (?:increase|hike|cut|declaration|suspension)|stock split|share offering|secondary offering|convertible|debt offering|notes offering|bond (?:sale|offering|issue)|sale-leaseback|leaseback|refinanc|refi\b|cmbs|cds spreads?|credit (?:default|spreads?)|financing|(?:puts?|plans?|commits?|invests?|to invest|spend(?:s|ing)?|bets?)\s+(?:\$[\d.,]+\s?(?:m|b|million|billion)|billions?)"),
    ("layoffs", r"layoff|lays? off|job cuts|cutting jobs|workforce reduction|restructuring plan|plant clos|store clos"),
    ("macro", r"\b(?:copper|crude|brent|wti|natural gas|gold price|silver|lithium|iron ore|wheat|corn|soybeans?|coffee|cocoa|sugar)\b.{0,60}(?:price|rall|surge|fall|drop|record|high|low|selloff|stockpile|supply)|oil (?:price|rall|slump)|\bopec\b|commodit"),
    ("legal_reg", r"lawsuit|sues?\b|sued|antitrust|\bftc\b|\bdoj\b|\bsec\b (?:charges|fines|probe)|fined|\bfine\b|overturn|settlement|regulator|investigation|\bban(?:s|ned)?\b|export (?:control|restriction|ban)|tariff|sanction|court|appeals|blacklist|ruling|class action|recall|\bfdic\b"),
    ("analyst", r"upgrad|downgrad|price target|initiates? coverage|reiterat|overweight|underweight|equal-weight|outperform|underperform|raises? target|cuts? target"),
    ("supply", r"supply chain|shortage|supplier|production (?:cut|halt|delay)|factory|plant (?:fire|shut)|capacity|shipment|backlog|order (?:book|intake)|chip (?:demand|supply)|take years|can take (?:years|months)|bottleneck|power (?:shortage|constraint)|buildout|runs? into (?:a )?(?:major )?(?:issue|problem|bottleneck)"),
    ("geopolitics", r"\b(?:iran|hormuz|houthis?|riyadh|taiwan|xi|trump-xi|ukraine|russia|kremlin|putin|gaza|israel|hamas|north korea|nato|missiles?|troops|ceasefire|unga|belarus|hong kong|beijing|pentagon|f-35|war|summit|kim jong)\b|\bus[- ]china\b|china[, ]+(?:and )?(?:us|u\.s\.)|(?:us|u\.s\.) and china"),
    ("product", r"fda (?:approves?|clears?|approval)|glitch|defect|flaw|malfunction|software (?:bug|issue)|launch|unveil|introduc|release[sd]?\b|rollout|roll(?:s|ed)? out|showcas|announces? (?:new|its)|beta\b|new (?:model|version|chip|product|feature|iphone|gpu)"),
    ("macro", r"\bfed\b|federal reserve|\becb\b|rate (?:cut|hike|decision)|global rates|higher rates|inflation|\bcpi\b|\bppi\b|jobs report|payrolls|gdp\b|unemployment|treasury yields?|bond yields?|yield curve|recession|central bank|krona|forex|currency"),
    ("index_change", r"s&p 500 (?:add|remov|inclusion|deletion)|added to (?:the )?(?:s&p|nasdaq-100|dow)|index rebalanc|joins (?:the )?s&p"),
]
